-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 16:56:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dans_tes_reves
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dans_tes_reves`.`presentation`;
DROP TABLE IF EXISTS `dans_tes_reves`.`series`;
DROP TABLE IF EXISTS `dans_tes_reves`.`files`;
DROP TABLE IF EXISTS `dans_tes_reves`.`creation`;
DROP TABLE IF EXISTS `dans_tes_reves`.`user`;

-- -----------------------------------------------------
-- Schema dans_tes_reves
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dans_tes_reves` DEFAULT CHARACTER SET utf8 ;
USE `dans_tes_reves` ;

-- -----------------------------------------------------
-- Table `dans_tes_reves`.`presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dans_tes_reves`.`presentation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dans_tes_reves`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dans_tes_reves`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dans_tes_reves`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dans_tes_reves`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(100) NOT NULL,
  `image_alt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dans_tes_reves`.`creation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dans_tes_reves`.`creation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `art-title` VARCHAR(45) NULL,
  `date` DATE NULL,
  `size` VARCHAR(45) NULL,
  `technical` VARCHAR(250) NULL,
  `story` VARCHAR(250) NULL,
  `series_id` INT NOT NULL,
  `files_id` INT NOT NULL,
  PRIMARY KEY (`id`, `series_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_creation_series1_idx` (`series_id` ASC) VISIBLE,
  INDEX `fk_creation_files1_idx` (`files_id` ASC) VISIBLE,
  CONSTRAINT `fk_creation_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `dans_tes_reves`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_creation_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `dans_tes_reves`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dans_tes_reves`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dans_tes_reves`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
